### ISSUE TITLE
Validation issue on Checkout in 1.7.7.0

### ISSUE THREAD

**Issue by bhavikvaghani** [prestarocket-agence/classic-rocket#207]
Hello,

While form validation in checkout, if there is any error button is getting disabled.

**Comment by jose-munoz-ahumada** [comment]
Hi, 

There is a new function in prestashop core checkout js 
![image](https://user-images.githubusercontent.com/16447141/103669999-ccb38c00-4f57-11eb-8e77-9ed7975e336d.png)

This disabled the button for prevent double click on form submit. This only works fine on forms with no front-end validation.

i've made this changes in _dev/js/components/form.js and works fine
![image](https://user-images.githubusercontent.com/16447141/103670640-962a4100-4f58-11eb-9304-09d69d770afc.png)

**Comment by bhavikvaghani** [comment]
Hey,

Thanks for the help. It works well now.

Here is the new added lines.
$(this).data('disabled', false);
$('button[type="submit"]', form).removeClass('disabled');

**Comment by tomasu777** [comment]
Thanks for the question and fix! @bhavikvaghani @jose-munoz-ahumada 

I'm strugling with theme.js compilation since i use gulp (where's only sass tasks) so i decided to try build my own gulp task for theme.js compilation from _dev but it just doesn't work.

`
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');
var replace = require('gulp-replace');
var autoprefixer = require('gulp-autoprefixer');
var uglify = require('gulp-uglify');
var pipeline = require('readable-stream').pipeline;

gulp.task('compress', function () {
    return pipeline(
        gulp.src('js/**/*.js'),
        uglify(),
        gulp.dest('../js/theme.js')
    );
});

gulp.task('watch', function(){
    gulp.watch('css/**/*.scss', gulp.series('sass','move'))
    gulp.watch('js/**/*.js'), gulp.series('compress')
});`

any one else is using gulp for js compilation for this theme and point me what i have done wrong ins this task?

**Comment by JaimeGarciaBahamonde** [comment]
I can reproduce the issue, and confirm that the fix provided by @bhavikvaghani works. Thanks!!

**Comment by prestarocket** [comment]
fix in https://github.com/prestarocket-agence/classic-rocket/tree/3.1.0
thx
